### ISSUE TITLE
Honeypot tests need to be restructured for Backdrop CMS

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/honeypot#5]
- Remove this from the .info file:

```
files[] = honeypot.test
```
- Add a directory in the module called `tests`
- move the honeypot.test file into the `tests` directory
- add a `honeypot.tests.info` file into the `tests` directory

See admin_bar module in core for a good example.

**Comment by herbdool** [comment]
Thanks Jen. I've restructured this. And removed a test class related to integration with Triggers.

I think I will try out the tests before making another release. Would also be good to breakup the one class into multiple ones since it seems to combine all combos into one. That would be good practice for me.

**Comment by herbdool** [comment]
Okay, I've fixed some issues with the tests and all tests are now passing. I think it's ready for minor release.
